/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.dao.*;
import com.mycompany.model.*;
import com.mycompany.utils.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hirraabdulmalik
 */
public class ViewPayRoll extends javax.swing.JFrame {
    private static List<Employee> employees;
    private static List<MessCharge> allMessCharges;
    private static List<OtherDeduction> allDeductions;
    private static List<Advance> allAdvances;
    private List<EmployeeSalary> employeeSalaries;
    String[] months = {
            "January", "February", "March", "April", "May", "June", 
            "July", "August", "September", "October", "November", "December"
        }; 
    /**
     * Creates new form ViewPayRoll
     */
    public ViewPayRoll() throws SQLException {
        initComponents();
        jComboBoxMonth.removeAllItems();
        for(String st : months){
            jComboBoxMonth.addItem(st);
        }
        employees = new EmployeeDAO().getAllEmployees();
        allMessCharges= new MessChargeDAO().getAllMessCharges();
        allDeductions =  OtherDeductionsDAO.getAllOtherDeductions();
        allAdvances = AdvanceDAO.getAllAdvances();
        employeeSalaries = new ArrayList<EmployeeSalary>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSpinnerYear = new javax.swing.JSpinner();
        jButtonGenerateSalary = new javax.swing.JButton();
        jButtonPaySalary = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonViewArchive = new javax.swing.JButton();
        jSpinnerYear1 = new javax.swing.JSpinner();
        jComboBoxMonth1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(jTable1);

        jSpinnerYear.setModel(new javax.swing.SpinnerListModel(new String[] {"2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033"}));

        jButtonGenerateSalary.setText("Generate");
        jButtonGenerateSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateSalaryActionPerformed(evt);
            }
        });

        jButtonPaySalary.setText("Pay Salaries");
        jButtonPaySalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaySalaryActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGenerateSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE)
                        .addComponent(jButtonPaySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPaySalary)
                    .addComponent(jButtonGenerateSalary)
                    .addComponent(jSpinnerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Pay Salaries", jPanel2);

        jButtonViewArchive.setText("Load");
        jButtonViewArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewArchiveActionPerformed(evt);
            }
        });

        jSpinnerYear1.setModel(new javax.swing.SpinnerListModel(new String[] {"2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033"}));

        jComboBoxMonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonViewArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 646, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewArchive)
                    .addComponent(jSpinnerYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(553, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Archive", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonPaySalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaySalaryActionPerformed
        // TODO add your handling code here:
        List<EmployeeSalary> empSalaries = GetEmployeeSalaryObjectsFromTableAfterEdit();
        EmployeeSalaryDAO empD = new EmployeeSalaryDAO();
        boolean success = true;
        for(EmployeeSalary empS : empSalaries){
            //double bonus, double totalSalary, int employeeID, Date salaryDate
            EmployeeSalary4DB emp4DB = new EmployeeSalary4DB(0, empS.getBonus(), empS.getTotalSalaryCalculated(), empS.getActualPaidSalary(), empS.getEmployeeId(),DateUtil.GetTodayAsString());

            try {
                empD.createEmployeeSalary(emp4DB);
                PutCarryForwardForAllEmployees(empS);
            } catch (SQLException ex) {
                Logger.getLogger(ViewPayRoll.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            AdvanceDAO.ResolveAllAdvance();
            OtherDeductionsDAO.ResolveAllOtherDeduction();
            MessChargeDAO.ResolveAllMessCharges();
        } catch (SQLException ex) {
            Logger.getLogger(ViewPayRoll.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this, success ? "All Salaries added successfully" : "Failed to add Salaries");
    }//GEN-LAST:event_jButtonPaySalaryActionPerformed

    private void jButtonGenerateSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateSalaryActionPerformed
        // TODO add your handling code here:
        setEmployeeSalaryTableModel(jTable1);
    }//GEN-LAST:event_jButtonGenerateSalaryActionPerformed

    private void jButtonViewArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewArchiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewArchiveActionPerformed
    public void setEmployeeSalaryTableModel(JTable table) {
        // Create a DefaultTableModel with column names
        // Create an instance of the custom table model
        EmployeeSalaryTableModel model = new EmployeeSalaryTableModel();
        //DefaultTableModel model = new DefaultTableModel();
        model.addColumn("EmployeeID");
        model.addColumn("Name");
        model.addColumn("Monthly Salary");
        model.addColumn("Bonus");
       model.addColumn("Previous Loan");
        model.addColumn("Advance during month");
        model.addColumn("Deduction");
        model.addColumn("Mess Bill");
        model.addColumn("Calculated Salary");
        model.addColumn("Actual paid");
        model.addColumn("Carry Forward");
        // Add rows from the List<Employee>
        for (Employee employee : employees) {

            int totalAdvance = 0;
            int totalDeductions = 0;
            int messBill = 0;
            int bonus = 0;
            totalAdvance = CalculateUtils.CalculateAdvance(allAdvances, employee, totalAdvance);
            totalDeductions = CalculateUtils.CalculateDeduction(allDeductions, employee, totalDeductions);
            messBill = CalculateUtils.CalculateMessCharges(allMessCharges, employee, messBill);
            double totalCalculatedSalary = employee.getSalaryDecided() + bonus - (totalAdvance + totalDeductions + messBill +employee.getPreviousLoan());
                                EmployeeSalary empSalary = new EmployeeSalary();
        empSalary.setName(employee.getName());
        empSalary.setEmployeeId(employee.getEmployeeID());
        empSalary.setBonus(bonus);
        //empSalary.setCarryForward(employee.getPreviousLoan());
        empSalary.setDecidedSalary(employee.getSalaryDecided());
        empSalary.setMessBill(messBill);
        empSalary.setOtherDeduction(totalDeductions);
        empSalary.setAdvance(totalAdvance);
        empSalary.setTotalSalaryCalculated(totalCalculatedSalary);
        empSalary.setMonth((String) jComboBoxMonth.getSelectedItem());
        empSalary.setYear((String) jSpinnerYear.getValue());
        empSalary.setPreviousLoan(employee.getPreviousLoan());
        employeeSalaries.add(empSalary);
            model.addRow(new Object[] {
                empSalary.getEmployeeId(),
                empSalary.getName(),
                empSalary.getDecidedSalary(),
                empSalary.getBonus(),
                empSalary.getPreviousLoan(),
                empSalary.getAdvance(),
                empSalary.getOtherDeduction(),
                empSalary.getMessBill(), 
                empSalary.getTotalSalaryCalculated(),
                0,0
            });
        }

        // Set the model to the JTable
        table.setModel(model);
        TableUtils.hideColumn(jTable1, 0);
    }
    private List<EmployeeSalary> GetEmployeeSalaryObjectsFromTableAfterEdit()
    {
        // Extracting data and converting to EmpSalary objects
        List<EmployeeSalary> empSalaries = new ArrayList<>();
        for (int row = 0; row < jTable1.getRowCount(); row++) {
            int id = (int) jTable1.getModel().getValueAt(row, 0);  // Get the hidden column data at row 0
            String name = (String) jTable1.getValueAt(row, 0);
            double decidedSalary = (Double) jTable1.getValueAt(row, 1);
            double bonus = (Double) jTable1.getValueAt(row, 2);
            double previousLoan = (Double) jTable1.getValueAt(row, 3);
            double advance = (Double) jTable1.getValueAt(row, 4);
            double otherDeduction = (Double) jTable1.getValueAt(row, 5);
            double messBill = (Double) jTable1.getValueAt(row, 6);
            double totalSalaryCalculated = (Double) jTable1.getValueAt(row, 7);
            Object ob1 = jTable1.getValueAt(row, 8);  // Object containing Integer
            Double actualPaidSalary = 0.0;
if (ob1 instanceof Integer) {
    actualPaidSalary = ((Integer) ob1).doubleValue();  // Proper conversion
}
else{
    actualPaidSalary = (Double) jTable1.getValueAt(row, 8);
}
            Object ob2 = jTable1.getValueAt(row, 9);  // Object containing Integer
            Double carryForward = 0.0;
if (ob2 instanceof Integer) {
    actualPaidSalary = ((Integer) ob2).doubleValue();  // Proper conversion
}
else{
    carryForward = (Double) jTable1.getValueAt(row, 9);
}

            
            EmployeeSalary empSalary = new EmployeeSalary(id,name, decidedSalary, bonus, previousLoan,
                                                  advance, otherDeduction, messBill, totalSalaryCalculated,actualPaidSalary,carryForward);
            empSalaries.add(empSalary);
        }
        return empSalaries;
    }    private void PutCarryForwardForAllEmployees(EmployeeSalary empS){
            
                    try {
                EmployeeDAO.updateCarryForwardForEmployee(empS.getCarryForward(), empS.getEmployeeId());
            } catch (SQLException ex) {
                Logger.getLogger(ViewPayRoll.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPayRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPayRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPayRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPayRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewPayRoll().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPayRoll.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonGenerateSalary;
    private javax.swing.JButton jButtonPaySalary;
    private javax.swing.JButton jButtonViewArchive;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxMonth1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerYear;
    private javax.swing.JSpinner jSpinnerYear1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
